export const jobOpenings = [
  {
    key: "leadInstructor",
    title: "Lead Coding Instructor",
    department: "Education",
    summary:
      "As a Lead Coding Instructor, you'll be responsible for delivering high-quality coding instruction to students ages 7–18. You will take ownership of the classroom experience, mentor junior instructors, and ensure every student is engaged and challenged appropriately.",
    responsibilities: [
      "Plan and lead dynamic coding lessons based on our curriculum, adapting instruction to various learning levels.",
      "Provide clear explanations of concepts such as loops, conditionals, variables, functions, and project logic.",
      "Model and reinforce best practices in code design, problem-solving, and debugging.",
      "Guide students through hands-on projects using Scratch, Python, JavaScript, or game development tools.",
      "Support, coach, and provide feedback to assistant instructors and teaching aides.",
      "Create a safe, inclusive classroom environment where all students feel welcome to ask questions and try new ideas.",
      "Track and report student progress, identify areas for improvement, and communicate updates with families.",
      "Participate in ongoing professional development and curriculum refinement.",
    ],
    requirements: [
      "Minimum 3 years of experience teaching youth in coding, STEM, or K–12 education.",
      "Proficiency in at least one of the following: JavaScript (including p5.js or React), Python, or Scratch.",
      "Experience in classroom management with strong communication and leadership skills.",
      "Confidence working with both beginning and advanced students in one class setting.",
      "Ability to adapt lessons for neurodiverse learners and students with varying language skills.",
    ],
    preferredSkills: [
      "Experience with Unity, Roblox Studio, or educational platforms like Code.org or Tynker.",
      "Degree in Computer Science, Education, or a related field (or equivalent experience).",
      "Familiarity with Universal Design for Learning (UDL) and accessibility best practices.",
      "Experience with project-based learning and inquiry-based instruction.",
    ],
    pay: "$35–$45/hour depending on experience and certifications",
    employmentType: "Part-time with possible full-time transition",
    location:
      "Orange, CA (in-person) + occasional remote teaching opportunities",
  },

  {
    key: "assistantInstructor",
    title: "Assistant Coding Instructor",
    department: "Education",
    summary:
      "The Assistant Coding Instructor helps lead instructors deliver engaging classes, supports individual student needs, and contributes to a positive learning experience. Ideal for college students, early-career educators, or those entering tech education.",
    responsibilities: [
      "Support lead instructors during class with setup, student assistance, and activity facilitation.",
      "Work one-on-one with students who need extra guidance or are ready for advanced challenges.",
      "Assist with reviewing student code, helping debug issues, and encouraging exploration.",
      "Help create a welcoming, inclusive learning environment by modeling respect, patience, and encouragement.",
      "Document attendance, student progress, and behavioral notes.",
      "Participate in training sessions and team meetings to improve teaching skills and curriculum understanding.",
    ],
    requirements: [
      "1+ year experience working with youth in a classroom, camp, or after-school setting.",
      "Basic understanding of computer programming concepts (block-based or text-based).",
      "Friendly, patient, and proactive communicator with students and families.",
      "Willingness to learn and grow under mentorship of lead instructors.",
      "Ability to adapt to different learning styles and support students with diverse needs.",
    ],
    preferredSkills: [
      "Current student pursuing a degree in Computer Science or Education.",
      "Familiarity with tools like Scratch, MakeCode, or introductory Python environments.",
      "Experience with classroom management or youth mentorship.",
      "Interest in pursuing a career in education, coding, or tech.",
    ],
    pay: "$20–$28/hour based on experience and responsibilities",
    employmentType: "Part-time",
    location: "Orange, CA (in-person) + possible remote roles",
  },

  {
    key: "curriculumDesigner",
    title: "Curriculum Developer – Computer Science",
    department: "Instructional Design",
    summary:
      "We’re looking for a Curriculum Developer to create engaging, project-driven coding content for students across various age groups. You'll work with instructors to pilot lessons, refine resources, and ensure high-quality, inclusive instruction across all our programs.",
    responsibilities: [
      "Design and document lesson plans, student projects, assessments, and instructor guides.",
      "Align content to appropriate grade levels, cognitive load, and national standards (like CSTA or ISTE).",
      "Collaborate with instructors to test lessons and incorporate feedback from real classrooms.",
      "Ensure curriculum is inclusive, accessible, and meets the needs of neurodiverse and ELL learners.",
      "Keep up with current edtech tools and trends to suggest new platforms or pedagogy.",
      "Create engaging multimedia resources, including videos, slides, and interactive activities.",
      "Contribute to the development of student-facing materials, including handouts and online resources.",
    ],
    requirements: [
      "2+ years in instructional design, curriculum development, or K–12 education with a tech focus.",
      "Portfolio of prior work demonstrating lesson creation and curriculum structure.",
      "Knowledge of HTML/CSS, JavaScript, Python, or other educational coding environments.",
      "Strong written communication and documentation skills.",
      "Experience with project-based learning and inquiry-based instruction.",
      "Ability to work independently and collaboratively in a remote team environment.",
      "Familiarity with Universal Design for Learning (UDL) and accessibility best practices.",
    ],
    preferredSkills: [
      "Experience using tools like Notion, Google Docs, Canva, or LMS platforms.",
      "Comfort with UX writing or technical documentation for kids/teens.",
      "Experience with game design, robotics, or other hands-on tech projects.",
      "Familiarity with coding education platforms like Scratch, Code.org, or Tynker.",
      "Experience with youth mentorship or teaching.",
    ],
    pay: "$30–$42/hour or contract-based project rates",
    employmentType: "Part-time or contract",
    location: "Remote (with optional visits to Orange, CA)",
  },

  {
    key: "programCoordinator",
    title: "Program Coordinator",
    department: "Operations",
    summary:
      "The Program Coordinator ensures that all classes, camps, and workshops run smoothly. This role includes communication with families, instructor scheduling, and managing the backend logistics that keep our programs running efficiently and professionally.",
    responsibilities: [
      "Coordinate class schedules, student rosters, and instructor assignments.",
      "Serve as point of contact for parent inquiries, tech issues, and instructor needs.",
      "Manage enrollment and billing systems using tools like Airtable, Stripe, and Calendly.",
      "Onboard new hires and ensure compliance with HR and safety procedures.",
      "Collect feedback from instructors and families to support continuous program improvement.",
      "Assist with marketing and outreach efforts to promote programs and increase enrollment.",
      "Support the development of new programs and initiatives based on community needs.",
      "Help organize events, workshops, and community outreach activities.",
      "Maintain accurate records of program participation, attendance, and feedback.",
      "Assist with data entry and reporting for program evaluation and improvement.",
      "Support the development of marketing materials and outreach efforts.",
      "Assist with event planning and logistics for workshops, camps, and community outreach.",
    ],
    requirements: [
      "2+ years of administrative or coordination experience in a school, camp, or edtech program.",
      "Strong project management and customer service skills.",
      "Familiarity with basic tech tools (Slack, Google Workspace, Zoom, spreadsheets).",
      "Excellent organizational and written communication skills.",
      "Ability to work independently and manage multiple tasks in a fast-paced environment.",
      "Experience with data entry and record-keeping.",
    ],
    preferredSkills: [
      "Experience in a fast-paced startup, nonprofit, or youth programming organization.",
      "Interest in coding education or youth STEM engagement.",
      "Familiarity with coding concepts or experience in a tech-related field.",
      "Experience with marketing, social media, or community outreach.",
      "Knowledge of project management tools (Trello, Asana, Airtable).",
      "Experience with event planning and logistics.",
      "Familiarity with customer relationship management (CRM) software.",
      "Experience with data analysis and reporting.",
    ],
    pay: "$24–$32/hour depending on experience",
    employmentType: "Part-time (with potential for full-time role)",
    location: "Hybrid – Orange, CA & remote",
  },
];
