import { CourseSchedule } from "@/lib/types/types";
// Grades K to 2
export const yearRoundSchedule: CourseSchedule[] = [
  {
    ageGroup: "Grades K to 2",
    schedules: [
      {
        courseName: "Code Through Stories",
        subtitle: "Animated Storytelling & Coding",
        next: ["Mini Makers"],
        schedule: [
          {
            format: "In-person",
            days: ["Saturday"],
            durationWeeks: 8,
            startTime: "10:00 AM",
            endTime: "11:00 AM",
          },
          {
            format: "Online",
            days: ["Wednesday"],
            durationWeeks: 8,
            startTime: "4:00 PM",
            endTime: "5:00 PM",
          },
        ],
        includes: ["Materials provided", "Online resources"],
        price: { online: 149, inPerson: 179 },
      },
      {
        courseName: "Bitsbox and Bots",
        subtitle: "Coding & Robotics",
        next: ["Code Through Stories"],
        schedule: [
          {
            format: "In-person",
            days: ["Sunday"],
            durationWeeks: 8,
            startTime: "10:00 AM",
            endTime: "11:00 AM",
          },
          {
            format: "Online",
            days: ["Thursday"],
            durationWeeks: 8,
            startTime: "4:00 PM",
            endTime: "5:00 PM",
          },
        ],
        includes: ["Materials provided", "Robotics kit"],
        price: { online: 149, inPerson: 179 },
      },
      {
        courseName: "Digital Discovery Lab",
        subtitle: "Hands-on Tech & Logic",
        next: ["Code Through Stories"],
        schedule: [
          {
            format: "In-person",
            days: ["Sunday"],
            durationWeeks: 8,
            startTime: "10:00 AM",
            endTime: "11:00 AM",
          },
          {
            format: "Online",
            days: ["Tuesday"],
            durationWeeks: 8,
            startTime: "4:00 PM",
            endTime: "5:00 PM",
          },
        ],
        includes: ["Materials provided", "Take-home activities"],
        price: { online: 149, inPerson: 179 },
      },
      {
        courseName: "Mini Makers",
        subtitle: "Robotics & Creative Coding",
        next: ["Game Builders Club"],
        schedule: [
          {
            format: "In-person",
            days: ["Saturday"],
            durationWeeks: 8,
            startTime: "1:00 PM",
            endTime: "2:00 PM",
          },
          {
            format: "Online",
            days: ["Monday"],
            durationWeeks: 8,
            startTime: "4:00 PM",
            endTime: "5:00 PM",
          },
        ],
        includes: ["Materials provided", "Project showcase"],
        price: { online: 149, inPerson: 179 },
      },
      {
        courseName: "Code and Play",
        subtitle: "Logic Games & Movement",
        next: ["Pattern Makers", "Code Through Stories"],
        schedule: [
          {
            format: "In-person",
            days: ["Sunday"],
            startTime: "1:00 PM",
            endTime: "2:00 PM",
            durationWeeks: 10,
          },
          {
            format: "Online",
            days: ["Saturday"],
            startTime: "1:00 PM",
            endTime: "2:00 PM",
            durationWeeks: 10,
          },
          {
            format: "Online",
            days: ["Sunday"],
            startTime: "1:00 PM",
            endTime: "2:00 PM",
            durationWeeks: 10,
          },
          {
            format: "In-person",
            days: ["Saturday"],
            startTime: "3:00 PM",
            endTime: "4:00 PM",
            durationWeeks: 10,
          },
        ],
        includes: ["Activity kit", "Digital badge"],
        price: { online: 149, inPerson: 179 },
      },
      {
        courseName: "Pattern Makers",
        subtitle: "Math & Logic Patterns",
        next: ["Digital Discovery Lab", "Tinker Time"],
        schedule: [
          {
            format: "In-person",
            days: ["Saturday"],
            startTime: "10:00 AM",
            endTime: "11:00 AM",
            durationWeeks: 10,
          },
          {
            format: "Online",
            days: ["Wednesday"],
            startTime: "4:00 PM",
            endTime: "5:00 PM",
            durationWeeks: 10,
          },
        ],
        includes: ["Materials provided", "Workbook"],
        price: { online: 149, inPerson: 179 },
      },
      {
        courseName: "Tinker Time",
        subtitle: "Robots & Sensory Coding",
        next: ["Mini Makers", "Code Through Stories"],
        schedule: [
          {
            format: "In-person",
            days: ["Sunday"],
            startTime: "1:00 PM",
            endTime: "2:00 PM",
            durationWeeks: 8,
          },
          {
            format: "Online",
            days: ["Thursday"],
            startTime: "4:00 PM",
            endTime: "5:00 PM",
            durationWeeks: 8,
          },
        ],
        includes: ["Materials provided", "Sensory toolkit"],
        price: { online: 149, inPerson: 179 },
      },
      {
        courseName: "AI Storytellers",
        subtitle: "AI-Powered Story Creation",
        next: ["Code Through Stories", "Mini Makers"],
        schedule: [
          {
            format: "In-person",
            days: ["Saturday"],
            durationWeeks: 8,
            startTime: "11:15 AM",
            endTime: "12:00 PM",
          },
          {
            format: "Online",
            days: ["Tuesday"],
            durationWeeks: 8,
            startTime: "4:00 PM",
            endTime: "4:45 PM",
          },
        ],
        includes: ["Materials provided", "AI tools access"],
        price: { online: 149, inPerson: 179 },
      },
      {
        courseName: "Sensory Circuits Lab",
        subtitle: "Hands-on Circuits & Sensors",
        next: ["Tinker Time", "Mini Makers"],
        schedule: [
          {
            format: "In-person",
            days: ["Sunday"],
            durationWeeks: 8,
            startTime: "11:15 AM",
            endTime: "12:00 PM",
          },
          {
            format: "Online",
            days: ["Friday"],
            durationWeeks: 8,
            startTime: "4:00 PM",
            endTime: "4:45 PM",
          },
        ],
        includes: ["Materials provided", "Circuit kit"],
        price: { online: 149, inPerson: 179 },
      },
    ],
  },
  // Grades 3 to 5
  {
    ageGroup: "Grades 3 to 5",
    schedules: [
      {
        courseName: "Game Builders Club",
        subtitle: "2D Game Development",
        next: ["Web Wonders", "App Explorers"],
        schedule: [
          {
            format: "Online",
            days: ["Saturday"],
            startTime: "10:00 AM",
            endTime: "11:30 AM",
            durationWeeks: 10,
          },
          {
            format: "In-person",
            days: ["Sunday"],
            startTime: "1:00 PM",
            endTime: "2:30 PM",
            durationWeeks: 10,
          },
        ],
        includes: ["Online resources", "Project feedback"],
        price: { online: 199, inPerson: 229 },
      },
      {
        courseName: "Web Wonders",
        subtitle: "Intro to Web Development",
        next: ["App Explorers"],
        schedule: [
          {
            format: "Online",
            days: ["Sunday"],
            startTime: "10:00 AM",
            endTime: "11:30 AM",
            durationWeeks: 10,
          },
          {
            format: "In-person",
            days: ["Saturday"],
            startTime: "2:00 PM",
            endTime: "3:30 PM",
            durationWeeks: 10,
          },
        ],
        includes: ["Online resources", "Templates"],
        price: { online: 199, inPerson: 229 },
      },
      {
        courseName: "App Explorers",
        subtitle: "Mobile App Creation",
        next: ["Creative Code with Art", "Code for Music"],
        schedule: [
          {
            format: "Online",
            days: ["Saturday"],
            startTime: "1:00 PM",
            endTime: "2:30 PM",
            durationWeeks: 10,
          },
          {
            format: "In-person",
            days: ["Sunday"],
            startTime: "3:00 PM",
            endTime: "4:30 PM",
            durationWeeks: 10,
          },
        ],
        includes: ["Online resources", "Design toolkit"],
        price: { online: 199, inPerson: 229 },
      },
      {
        courseName: "Creative Code with Art",
        subtitle: "Generative Art with Code",
        next: ["Code for Music", "Code a Storybook"],
        schedule: [
          {
            format: "Online",
            days: ["Sunday"],
            startTime: "3:00 PM",
            endTime: "4:30 PM",
            durationWeeks: 10,
          },
          {
            format: "In-person",
            days: ["Saturday"],
            startTime: "11:00 AM",
            endTime: "12:30 PM",
            durationWeeks: 10,
          },
        ],
        includes: ["Online resources", "Art showcase"],
        price: { online: 199, inPerson: 229 },
      },
      {
        courseName: "Code for Music",
        subtitle: "Music & Audio Coding",
        next: ["Creative Code with Art", "Game Studio"],
        schedule: [
          {
            format: "Online",
            days: ["Saturday"],
            startTime: "3:00 PM",
            endTime: "4:00 PM",
            durationWeeks: 10,
          },
          {
            format: "In-person",
            days: ["Sunday"],
            startTime: "11:00 AM",
            endTime: "12:00 PM",
            durationWeeks: 10,
          },
        ],
        includes: ["Online resources", "Audio samples"],
        price: { online: 199, inPerson: 229 },
      },
      {
        courseName: "Code a Storybook",
        subtitle: "Interactive Storytelling",
        next: ["Creative Code with Art"],
        schedule: [
          {
            format: "Online",
            days: ["Sunday"],
            startTime: "4:30 PM",
            endTime: "5:30 PM",
            durationWeeks: 10,
          },
          {
            format: "In-person",
            days: ["Saturday"],
            startTime: "12:30 PM",
            endTime: "1:30 PM",
            durationWeeks: 10,
          },
        ],
        includes: ["Online resources", "Digital publishing"],
        price: { online: 199, inPerson: 229 },
      },
      {
        courseName: "AI Playground",
        subtitle: "Creative AI Projects",
        next: ["AI Basics", "Creative Code with Art"],
        schedule: [
          {
            format: "Online",
            days: ["Saturday"],
            durationWeeks: 10,
            startTime: "11:45 AM",
            endTime: "12:45 PM",
          },
          {
            format: "In-person",
            days: ["Sunday"],
            durationWeeks: 10,
            startTime: "2:00 PM",
            endTime: "3:00 PM",
          },
        ],
        includes: ["Online resources", "Project gallery"],
        price: { online: 199, inPerson: 229 },
      },
      {
        courseName: "Inventing Workshop",
        subtitle: "Microcontrollers & Prototyping",
        next: ["Game Studio", "Unity Game Dev 6 to 8"],
        schedule: [
          {
            format: "In-person",
            days: ["Sunday"],
            durationWeeks: 10,
            startTime: "11:45 AM",
            endTime: "12:45 PM",
          },
          {
            format: "Online",
            days: ["Wednesday"],
            durationWeeks: 10,
            startTime: "4:00 PM",
            endTime: "5:00 PM",
          },
        ],
        includes: ["Materials provided", "Project showcase"],
        price: { online: 199, inPerson: 229 },
      },
      {
        courseName: "AI Storytellers",
        subtitle: "AI-Powered Story Creation",
        next: ["Code Through Stories", "Mini Makers"],
        schedule: [
          {
            format: "In-person",
            days: ["Saturday"],
            durationWeeks: 8,
            startTime: "11:15 AM",
            endTime: "12:00 PM",
          },
          {
            format: "Online",
            days: ["Tuesday"],
            durationWeeks: 8,
            startTime: "4:00 PM",
            endTime: "4:45 PM",
          },
        ],
        includes: ["Materials provided", "AI tools access"],
        price: { online: 199, inPerson: 229 },
      },
    ],
  },
  // Grades 6 to 8
  {
    ageGroup: "Grades 6 to 8",
    schedules: [
      {
        courseName: "Game Studio",
        subtitle: "Advanced Game Development",
        next: ["Database Basics", "Unity Game Dev 6 to 8"],
        schedule: [
          {
            format: "Online",
            days: ["Saturday", "Sunday"],
            startTime: "10:00 AM",
            endTime: "12:00 PM",
            durationWeeks: 12,
          },
          {
            format: "In-person",
            days: ["Saturday"],
            startTime: "2:00 PM",
            endTime: "4:00 PM",
            durationWeeks: 12,
          },
        ],
        includes: ["Online resources", "Project review"],
        price: { online: 249, inPerson: 279 },
      },
      {
        courseName: "Unity Game Dev 6 to 8",
        subtitle: "Unity & C# Game Design",
        next: ["Game Studio", "Animation and Game Dev"],
        schedule: [
          {
            format: "Online",
            days: ["Sunday", "Wednesday"],
            startTime: "10:00 AM",
            endTime: "12:00 PM",
            durationWeeks: 12,
          },
          {
            format: "In-person",
            days: ["Saturday"],
            startTime: "4:00 PM",
            endTime: "6:00 PM",
            durationWeeks: 12,
          },
        ],
        includes: ["Online resources", "Asset pack"],
        price: { online: 249, inPerson: 279 },
      },
      {
        courseName: "Interactive Elements",
        subtitle: "JavaScript & APIs",
        next: ["Frontend Fundamentals"],
        schedule: [
          {
            format: "Online",
            days: ["Saturday", "Monday"],
            startTime: "1:00 PM",
            endTime: "2:30 PM",
            durationWeeks: 7,
          },
          {
            format: "In-person",
            days: ["Sunday"],
            startTime: "11:00 AM",
            endTime: "12:30 PM",
            durationWeeks: 12,
          },
        ],
        includes: ["Online resources", "Sample projects"],
        price: { online: 249, inPerson: 279 },
      },
      {
        courseName: "Frontend Fundamentals",
        subtitle: "HTML, CSS & JS Basics",
        next: [
          "Nextjs Essentials",
          "Full Stack Foundations",
          "Interactive Elements",
        ],
        schedule: [
          {
            format: "Online",
            days: ["Sunday"],
            startTime: "1:00 PM",
            endTime: "2:30 PM",
            durationWeeks: 12,
          },
          {
            format: "In-person",
            days: ["Saturday"],
            startTime: "10:00 AM",
            endTime: "11:30 AM",
            durationWeeks: 12,
          },
        ],
        includes: ["Online resources", "Project templates"],
        price: { online: 249, inPerson: 279 },
      },
      {
        courseName: "AI Explorers",
        subtitle: "Intro to Machine Learning",
        next: ["AI Basics", "Simulators and Physics"],
        schedule: [
          {
            format: "Online",
            days: ["Saturday"],
            durationWeeks: 12,
            startTime: "2:45 PM",
            endTime: "3:45 PM",
          },
          {
            format: "In-person",
            days: ["Sunday"],
            durationWeeks: 12,
            startTime: "11:00 AM",
            endTime: "12:00 PM",
          },
        ],
        includes: ["Online resources", "Data sets"],
        price: { online: 249, inPerson: 279 },
      },
      {
        courseName: "Smart Devices Lab",
        subtitle: "IoT & Automation",
        next: ["Unity Game Dev 6 to 8", "Database Basics"],
        schedule: [
          {
            format: "In-person",
            days: ["Sunday"],
            durationWeeks: 12,
            startTime: "2:45 PM",
            endTime: "3:45 PM",
          },
          {
            format: "Online",
            days: ["Wednesday"],
            durationWeeks: 12,
            startTime: "4:00 PM",
            endTime: "5:00 PM",
          },
        ],
        includes: ["Materials provided", "Automation project"],
        price: { online: 249, inPerson: 279 },
      },
      {
        courseName: "Web Dev and App Creation",
        subtitle: "Web & Mobile Development",
        next: ["Game Studio", "Unity Game Dev 6 to 8"],
        schedule: [
          {
            format: "In-person",
            days: ["Saturday"],
            durationWeeks: 12,
            startTime: "2:45 PM",
            endTime: "3:45 PM",
          },
          {
            format: "Online",
            days: ["Thursday"],
            durationWeeks: 12,
            startTime: "4:00 PM",
            endTime: "5:00 PM",
          },
        ],
        includes: ["Materials provided", "App builder access"],
        price: { online: 249, inPerson: 279 },
      },
      {
        courseName: "UX UI Design",
        subtitle: "User Experience & Interface Design",
        next: ["Interactive Elements", "Frontend Fundamentals"],
        schedule: [
          {
            format: "In-person",
            days: ["Saturday"],
            durationWeeks: 12,
            startTime: "2:45 PM",
            endTime: "3:45 PM",
          },
          {
            format: "Online",
            days: ["Monday"],
            durationWeeks: 12,
            startTime: "4:00 PM",
            endTime: "5:00 PM",
          },
        ],
        includes: ["Materials provided", "Project feedback"],
        price: { online: 249, inPerson: 279 },
      },
    ],
  },
  // Grades 9 to 12
  {
    ageGroup: "Grades 9 to 12",
    schedules: [
      {
        courseName: "Nextjs Essentials",
        subtitle: "Advanced React & Next.js",
        next: [
          "Advanced Backend and DevOps",
          "Startup Studio",
          "Advanced Web Dev",
        ],
        schedule: [
          {
            format: "Online",
            days: ["Saturday", "Sunday", "Wednesday"],
            startTime: "10:00 AM",
            endTime: "12:00 PM",
            durationWeeks: 14,
          },
          {
            format: "In-person",
            days: ["Saturday"],
            startTime: "2:00 PM",
            endTime: "4:00 PM",
            durationWeeks: 14,
          },
        ],
        includes: ["Online resources", "Deployment guides"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Simulators and Physics",
        subtitle: "Coding Real-World Systems",
        next: [
          "Application Programming Interfaces and Integrations",
          "Database Basics",
        ],
        schedule: [
          {
            format: "Online",
            days: ["Sunday", "Wednesday"],
            startTime: "10:00 AM",
            endTime: "12:00 PM",
            durationWeeks: 14,
          },
          {
            format: "In-person",
            days: ["Saturday"],
            startTime: "4:00 PM",
            endTime: "6:00 PM",
            durationWeeks: 14,
          },
        ],
        includes: ["Online resources", "Simulation toolkit"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Full Stack Foundations",
        subtitle: "Dynamic Web Projects",
        next: [
          "Application Programming Interfaces and Integrations",
          "Database Basics",
          "Advanced Web Dev",
        ],
        schedule: [
          {
            format: "Online",
            days: ["Saturday"],
            startTime: "1:00 PM",
            endTime: "3:00 PM",
            durationWeeks: 14,
          },
          {
            format: "In-person",
            days: ["Sunday"],
            startTime: "10:00 AM",
            endTime: "12:00 PM",
            durationWeeks: 14,
          },
        ],
        includes: ["Online resources", "Project templates"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Application Programming Interfaces and Integrations",
        subtitle: "Connecting to the Web",
        next: ["Nextjs Essentials", "Startup Studio", "Database Basics"],
        schedule: [
          {
            format: "Online",
            days: ["Sunday", "Wednesday", "Thursday"],
            startTime: "1:00 PM",
            endTime: "3:00 PM",
            durationWeeks: 16,
          },
          {
            format: "In-person",
            days: ["Saturday"],
            startTime: "11:00 AM",
            endTime: "1:00 PM",
            durationWeeks: 16,
          },
        ],
        includes: ["Online resources", "Sample integrations"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Database Basics",
        subtitle: "Data & Storage",
        next: [
          "Application Programming Interfaces and Integrations",
          "Advanced Backend and DevOps",
        ],
        schedule: [
          {
            format: "Online",
            days: ["Friday", "Wednesday", "Thursday"],
            startTime: "1:00 PM",
            endTime: "3:00 PM",
            durationWeeks: 14,
          },
          {
            format: "In-person",
            days: ["Sunday"],
            startTime: "2:00 PM",
            endTime: "4:00 PM",
            durationWeeks: 14,
          },
        ],
        includes: ["Online resources", "CRUD exercises"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Startup Studio",
        subtitle: "Tech Entrepreneurship",
        next: ["Nextjs Essentials", "AI Basics", "Startup Accelerator"],
        schedule: [
          {
            format: "Online",
            days: ["Sunday", "Saturday"],
            startTime: "3:00 PM",
            endTime: "5:00 PM",
            durationWeeks: 16,
          },
          {
            format: "In-person",
            days: ["Saturday"],
            startTime: "10:00 AM",
            endTime: "12:00 PM",
            durationWeeks: 16,
          },
        ],
        includes: ["Online resources", "Mentorship"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "AI Basics",
        subtitle: "Intro to Artificial Intelligence",
        next: ["Startup Studio", "Nextjs Essentials (Grades 9 to 12)"],
        schedule: [
          {
            format: "Online",
            days: ["Saturday", "Friday", "Sunday"],
            startTime: "7:30 PM",
            endTime: "9:00 PM",
            durationWeeks: 20,
          },
          {
            format: "In-person",
            days: ["Sunday"],
            startTime: "11:00 AM",
            endTime: "12:30 PM",
            durationWeeks: 20,
          },
        ],
        includes: ["Online resources", "AI sandbox"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Advanced Backend and DevOps",
        subtitle: "Databases, APIs & Deployment",
        next: ["Startup Accelerator"],
        schedule: [
          {
            format: "Online",
            days: ["Monday", "Wednesday", "Friday"],
            startTime: "7:30 PM",
            endTime: "9:00 PM",
            durationWeeks: 16,
          },
          {
            format: "In-person",
            days: ["Saturday"],
            startTime: "4:00 PM",
            endTime: "5:30 PM",
            durationWeeks: 16,
          },
        ],
        includes: ["Online resources", "DevOps toolkit"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Startup Accelerator",
        subtitle: "Capstone Product Launch",
        next: [],
        schedule: [
          {
            format: "In-person",
            days: ["Saturday", "Sunday"],
            startTime: "3:00 PM",
            endTime: "5:00 PM",
            durationWeeks: 16,
          },
          {
            format: "Online",
            days: ["Friday"],
            startTime: "6:00 PM",
            endTime: "8:00 PM",
            durationWeeks: 16,
          },
        ],
        includes: ["Mentorship", "Demo day"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Advanced Web Dev",
        subtitle: "React, TypeScript & SSR",
        next: ["Full Stack Foundations", "Nextjs Essentials", "AI Basics"],
        schedule: [
          {
            format: "Online",
            days: ["Saturday", "Sunday"],
            startTime: "1:00 PM",
            endTime: "3:00 PM",
            durationWeeks: 16,
          },
          {
            format: "In-person",
            days: ["Sunday"],
            startTime: "10:00 AM",
            endTime: "12:00 PM",
            durationWeeks: 16,
          },
        ],
        includes: ["Online resources", "Code review"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Capstone Project",
        subtitle: "Full-Stack Project Build",
        next: ["Startup Accelerator"],
        schedule: [
          {
            format: "In-person",
            days: ["Saturday", "Sunday"],
            startTime: "6:00 PM",
            endTime: "9:00 PM",
            durationWeeks: 16,
          },
          {
            format: "Online",
            days: ["Thursday"],
            startTime: "5:00 PM",
            endTime: "8:00 PM",
            durationWeeks: 16,
          },
        ],
        includes: ["Mentorship", "Portfolio review"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Animation and Game Dev",
        subtitle: "Blender & Unity 3D",
        next: ["Game Studio", "Unity Game Dev 9 to 12"],
        schedule: [
          {
            format: "In-person",
            days: ["Saturday", "Sunday"],
            startTime: "1:00 PM",
            endTime: "3:00 PM",
            durationWeeks: 16,
          },
          {
            format: "Online",
            days: ["Wednesday"],
            startTime: "4:00 PM",
            endTime: "6:00 PM",
            durationWeeks: 16,
          },
        ],
        includes: ["Online resources", "3D asset pack"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Algorithms",
        subtitle: "AP/College CS Preparation",
        next: ["Internship Program"],
        schedule: [
          {
            format: "Online",
            days: ["Saturday", "Sunday"],
            startTime: "1:00 PM",
            endTime: "3:00 PM",
            durationWeeks: 20,
          },
          {
            format: "In-person",
            days: ["Saturday"],
            startTime: "10:00 AM",
            endTime: "12:00 PM",
            durationWeeks: 20,
          },
        ],
        includes: ["Online resources", "Exam prep"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Internship Program",
        subtitle: "Real-World Tech Experience",
        next: [],
        schedule: [
          {
            format: "In-person",
            days: ["Flexible"],
            startTime: "Flexible",
            endTime: "Flexible",
            durationWeeks: 8,
          },
          {
            format: "Online",
            days: ["Flexible"],
            startTime: "Flexible",
            endTime: "Flexible",
            durationWeeks: 8,
          },
        ],
        includes: ["Mentorship", "Reference letter"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Entrepreneurship Basics",
        subtitle: "Business & Product Design",
        next: ["Internship Program"],
        schedule: [
          {
            format: "In-person",
            days: ["Saturday", "Sunday"],
            startTime: "1:00 PM",
            endTime: "3:00 PM",
            durationWeeks: 16,
          },
          {
            format: "Online",
            days: ["Wednesday"],
            startTime: "4:00 PM",
            endTime: "6:00 PM",
            durationWeeks: 16,
          },
        ],
        includes: ["Mentorship", "Pitch deck template"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Machine Learning Studio",
        subtitle: "Building Real ML Models",
        next: ["AI Basics", "Simulators and Physics"],
        schedule: [
          {
            format: "In-person",
            days: ["Saturday"],
            durationWeeks: 16,
            startTime: "11:00 AM",
            endTime: "12:30 PM",
          },
          {
            format: "Online",
            days: ["Friday"],
            durationWeeks: 16,
            startTime: "4:00 PM",
            endTime: "5:30 PM",
          },
        ],
        includes: ["Online resources", "ML datasets"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Robotics Engineering",
        subtitle: "Advanced Robotics & Automation",
        next: ["Startup Studio", "Advanced Backend and DevOps"],
        schedule: [
          {
            format: "In-person",
            days: ["Sunday"],
            durationWeeks: 16,
            startTime: "11:00 AM",
            endTime: "12:30 PM",
          },
          {
            format: "Online",
            days: ["Thursday"],
            durationWeeks: 16,
            startTime: "4:00 PM",
            endTime: "5:30 PM",
          },
        ],
        includes: ["Materials provided", "Competition prep"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Unity Game Dev 9 to 12",
        subtitle: "Advanced Game Development with Unity",
        next: ["Game Studio", "Animation and Game Dev"],
        schedule: [
          {
            format: "In-person",
            days: ["Saturday", "Sunday"],
            startTime: "1:00 PM",
            endTime: "3:00 PM",
            durationWeeks: 16,
          },
          {
            format: "Online",
            days: ["Monday"],
            startTime: "4:00 PM",
            endTime: "6:00 PM",
            durationWeeks: 16,
          },
        ],
        includes: ["Online resources", "Asset store credits"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Capstone Accelerator",
        subtitle: "Project Development & Mentorship",
        next: ["Startup Accelerator"],
        schedule: [
          {
            format: "In-person",
            days: ["Saturday", "Sunday"],
            startTime: "3:00 PM",
            endTime: "5:00 PM",
            durationWeeks: 16,
          },
          {
            format: "Online",
            days: ["Friday"],
            startTime: "6:00 PM",
            endTime: "8:00 PM",
            durationWeeks: 16,
          },
        ],
        includes: ["Mentorship", "Portfolio review"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "AI and Robotics Introduction",
        subtitle: "Intro to AI & Robotics",
        next: ["AI Basics", "Machine Learning Studio"],
        schedule: [
          {
            format: "In-person",
            days: ["Saturday"],
            durationWeeks: 16,
            startTime: "11:00 AM",
            endTime: "12:30 PM",
          },
          {
            format: "Online",
            days: ["Tuesday"],
            durationWeeks: 16,
            startTime: "4:00 PM",
            endTime: "5:30 PM",
          },
        ],
        includes: ["Materials provided", "AI toolkit"],
        price: { online: 349, inPerson: 399 },
      },
      {
        courseName: "Game Design and Development",
        subtitle: "Game Design Principles & Development",
        next: ["Game Studio", "Unity Game Dev 9 to 12"],
        schedule: [
          {
            format: "In-person",
            days: ["Saturday", "Sunday"],
            startTime: "1:00 PM",
            endTime: "3:00 PM",
            durationWeeks: 16,
          },
          {
            format: "Online",
            days: ["Thursday"],
            startTime: "4:00 PM",
            endTime: "6:00 PM",
            durationWeeks: 16,
          },
        ],
        includes: ["Online resources", "Project showcase"],
        price: { online: 349, inPerson: 399 },
      },
    ],
  },
];
